### ISSUE TITLE
usb handling device error

### ISSUE THREAD

**Issue by adharshmt** [adharshmt/WebScrapping#2]
Failed to read descriptor from node connection: A device attached to the system is not functioning

error comes up

**Comment by adharshmt** [comment]
this fixes the issue


from selenium.webdriver.chrome.options import Options

options = Options()
options.add_experimental_option('excludeSwitches', ['enable-logging'])

**Comment by sachinjoseph** [comment]
@adharshmt Can you link the `StackOverflow` answer that helped resolve this issue? Also mention it in a comment in `verge.py`.
