### ISSUE TITLE
proper way to take links

### ISSUE THREAD

**Issue by adharshmt** [adharshmt/WebScrapping#3]
unable to find a proper way to take links from https://www.theverge.com/

find_elements_by_class_name('c-entry-box--compact__image-wrapper')

this is what is being used. this seems to be a weird workaround and not proper.

**Comment by sachinjoseph** [comment]
Your approach works, To get all the the title, we could select the title element of each box, rather than extracting the link from the preview image:

```python
contents = driver.find_elements_by_class_name('c-entry-box--compact__title')
for content in contents:
    elem = content.find_element_by_tag_name('a')
    href = elem.get_attribute('href')
    print(elem.text)
    print(href)
    print()
```

**Comment by adharshmt** [comment]
Works like a charm.

TY.
